export const localString = {
  name: {
    live365: '365Live',
  },
  // header
  header: {
    nearBy: 'Near By',
    recommendation: 'Recommendations',
    listEvent: 'List an Event',
    loginSignup: 'Log In/Sign Up',
    rsvp: 'RSVPs',
    rsvpChecked: 'Checked-in-RSVPs',
    home: 'Home',
    location: 'Venue/Location',
    event: 'Event',
    events: 'Events',
    notification: 'Notification',
    preferences: 'Preferences',
    manageUsers: 'Manage Users',
    getPaid: 'Get Paid',
    help: 'Help',
    share: 'Share',
    profile: 'Profile',
    changePassword: 'Change Password',
    faqs: 'FAQs',
    termsConditions: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    favourite: 'Favorite',
    bookedEvents: 'Booked Events',
    settings: 'Settings',
    contactUs: 'Contact Us',
    aboutUs: 'About Us',
    logout: 'Logout',
    payment: 'Payment Methods',
    createTicket: 'Create Tickets',
    selectVenue: 'Select Venue',
    payments: 'All Payments',
    message: 'Message',
    today: 'Today',
    tomorrow: 'Tomorrow',
    thisWeek: 'This Week',
    yourEvent: 'Your Event'
  },
  // footer
  footer: {
    downloadNow: 'Download the App Now!',
    downloadOn: 'Download on the',
    appStore: 'App Store',
    getItOn: 'Get it on',
    googlePlay: 'Google Play',
    company: 'Company',
    aboutUs: 'about us',
    contactUs: 'contact us',
    becomePartner: 'become partner',
    browserEvent: 'browse event',
    trmCondition: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    helpSupport: 'Help & Support',
    faq: 'FAQ',
    copyright1: 'Copyright ©',
    copyright2: '365Live Inc',
    forYou: 'For You',
    footerContent: 'Discover Events Near You',
    footerContentTopLine: 'FIND SOMETHING FUN TO DO',
    legal: 'Legal',
    more: 'More',
    becomePartnerlogout: 'Do you want to logout? Register as a Partner',
    alredyPartner: 'You are already a Partner'
  },
  // register
  register: {
    google: 'Google',
    facebook: 'Facebook',
    apple: 'Apple',
    registerAs: 'Register as',
    forgotPassword: 'Forgot Password?',
    alreadyAccount: 'Already have an account?',
    login: 'Log in',
    loggedin: 'Login',
  },
  // for all labels
  labels: {
    name: 'Name',
    email: 'Email',
    PhoneNumber: 'Mobile Number',
    password: 'Password',
    address: 'Address',
    city: 'City',
    state: 'State',
    zip: 'Zip',
    shortInfo: 'Short info',
    url: 'URL'
  },
  // validations
  validations: {
    name: 'Name is required',
    onlyChar:'Url only should be characters and Number',
    nameMin2Length: 'Minimum Character limit is 5',
    nameMinLength: 'Enter valid name minimum 3 characters is required',
    nameMaxLength: 'Enter valid name maximum 30 characters is required',
    invalidName: 'Entered name is invalid',
    email: 'Email is required',
    cityOnlyCharacter: 'City only should be characters',
    password: 'Password is required',
    passwordMinLength: 'Your password must be at least 8 characters',
    passwordMaxLength: 'Your password must not be more then 30 characters',
    atLeastOneNumber: 'Your password must have at least 1 number, minimum 8 and maximum 30 characters',
    whiteSpace: 'White space not allowed',
    characterExceed: 'Description should be less than 200 Words',
    validEmail: 'Enter Valid Email',
    otpRequired: 'OTP is required',
    wrongOtp: 'Entered OTP is invalid.',
    validOtp: 'Enter Valid OTP',
    address: 'Address is required',
    city: 'City is required',
    state: 'State is required',
    validMaxLength: 'Maximum Character limit is 250',
    validMinLength: 'Minimum Character limit is 20',
    zip: 'Zip is required',
    validZip: 'Enter valid zip',
    validMaxLength2: 'Maximum Character limit is 50',
    validUrl: 'Enter valid URL like https://www.google.com',
    onlyDigits: 'Only digits are allowed',
    onlyCharacter: 'Only characters are allowed',
    search: 'search length should be greater than 5',
    ticketNameError: 'Ticket name is required',
    priceError: 'Price is required',
    descriptionError: 'Description is required',
    dateError: 'Please Select Date',
    timeError: 'Please Select Time',
    quantityError: 'Ticket quantity is required',
    tablesError: '** Numbers of Tables is required ',
    personError: '** Numbers of person is required ',
    ticketNameLengthError: 'Ticket name length should be less than 50',
    categoryNameLengthError: 'Category name length should be less than 25',
    ticketMaxQuantity: 'Maximum limit exceed',
    descriptionMinLength: 'Too short !',
    dateValidator: 'Start-date should be less than End-date',
    categoryNameError: 'Category name is required',
    subCategory: 'Sub Category is required',
    occuredOn: 'Occured on day is required',
    eventName: 'Event name is required',
    eventNameLengthError: 'Event name length should be less than 75',
    venue: 'Venue is required',
    eventDetails: 'Event details is required',
    eventDetailsMinLength: 'Event details length should be greater than 50',
    eventDetailsMaxLength: 'Event details length should be less than 4000',
    addOnInfo: 'Add on info is required',
    addOnInfoMinLength: 'Add on info length should be greater than 0',
    addOnInfoMaxLength: 'Add on info length should be less than 250',
    image: 'Image is required',
    startDate: 'Start date is required',
    endDate: 'End date is required',
    endDateGreaterThen: 'End date should be greater than start date',
    startTime: 'Start time is required',
    endTime: 'End Time is required',
    validDate: 'Please Enter Valid Date',
    TicketNumber: 'Please Enter Ticket Number',
    addReview: 'Please Add Review',
    valueBeeetween: 'Enter Value between 0-100'
  },
  // validations or event
  validations_error: {
    name: [
      { type: 'required', message: 'New Password is required' },
      { type: 'minlength', message: 'Password must be at least 6 character long' },
    ],
  },
  // otp verification screen
  verification: {
    verificationHeading: 'Email Verification',
    subText: 'Enter the 4-digit code that was sent to your email.',
    resendCode: 'Resend code in',
    clickToResend: 'Click',
  },
  // submit info screen
  submitInfo: {
    submitInfoHeading: 'Additional Info',
    accountCreation: 'Account Creation Success!',
    submitPreference: 'Submit your Preferences',
    into: 'What are you into?',
    prefrenceSubText: 'Let us help you find the things you like.'
  },
  // all buttons
  buttons: {
    verify: 'Verify',
    submit: 'Submit',
    continue: 'Continue',
    cancel: 'Cancel',
    back: 'back',
    next: 'Next',
    return: 'Return',
    resetSucessfullLogin: 'Login Now!',
    process: 'Process',
    update: 'Update',
    Yes: 'Yes',
    No: 'No',
    skip: 'Skip',
    gotoPreference: 'Go to Preferences',
    invite: 'Invite',
    close: 'Close',
    contact: 'Contact',
    submitevent: 'Submit Event',
    done: 'Done',
    review: 'Write a review',
    sendMessage: 'Send message',
    createTicket: 'Create Ticket'
  },
  // all placeholder
  placeholder: {
    placeholderName: 'Enter Name',
    placeholderEmail: 'Enter Email',
    placeholderPassword: 'Enter Password',
    placeholderAddress: 'Enter Address',
    placeholderCity: 'Enter city, state',
    placeholderForCity: 'Enter City',
    placeholderForState: 'Enter State',
    placeholderZip: 'Enter Zip Code',
    placeholderURL: 'Enter URL',
    placeholderShortInfo: 'Write Here',
    placeholderoldpwd: 'Old Password',
    placeholdernewpwd: 'New Password',
    placeholderconfirmpwd: 'Confirm Password',
    placeholderEnterContactNumber: 'Enter Contact number (e.g.+91XXXXXXXX)',
    placeholderEnterAddress: 'Enter your Address',
    placeholderEnterWebsiteURL: 'Enter Website URL',
    placeholderEnterWebsiteURL2: 'Enter Website URL',
  },

  // all user type
  userType: {
    user: 'User',
    partner: 'Partner',
    venueOwner: 'Venue Owner',
    host: 'Host',
    promoter: 'Promoter',
    lowercaseUser: 'customer',
    lowerCaseVenuer: 'venuer',
    lowerCasePromoter: 'promoter',
    lowerCaseHost: 'host',
    guestUser: 'guestUser',
    member: 'member'
  },

  // for preferences screen
  preferences: {
    sectionHeading: 'Select category',
  },

  // for all model
  alert: {
    alertHeading: 'Alert!',
    accountAlreadyExists: 'Account already exists.',
    alertLocation: 'Please Allow Location.',
    alertDelete: 'Do you really want to delete ticket ?',
    cancelTicket: 'Do you really want to cancel ticket ?',
    selectPreference: 'Please select preferences',
    validLatLong: 'Enter Valid Address',
    inviteSuccess: 'Invite Sent Successfully',
    success: 'Success',
    account: 'Account :',
    mobVerification: 'Mobile Verification',
    mobContent: 'You need to perform one time verification of your Mobile number. It is required for booking tickets.',
    mobOTPMsg: 'Enter 4 digit code that is sent to ',
    Note: 'Note: If you wish to change this Mobile number, you can go in your profile settings',
  },
  login: {
    notHavingAcc: 'Don\'t have an account?',
    login: 'Login',
    register: 'Register',
    emailId: 'Email'
  },

  // home page
  home: {
    upcomingEvent: 'Upcoming Events',
    pastEvent: 'Past Events',
    rsvpGuestList: 'RSVP/Guest List',
    createEvent: 'Create Event',
    nearByEvents: 'Discover Events Near You',
    featuredEvents: 'Featured Events',
    popularSearch: 'Popular Searches',
    resetFilter: 'Reset Filters',
    upComingEvents: 'Upcoming Events',
    pastEvents: 'Past Events',
    welcome: 'Welcome',
    distance: 'Distance',
    miles: 'Miles',
    admissionCost: 'Admission Cost',
    free: 'Free',
    viewAll: 'View All',
    SeeMore: 'See More >>>',
    Prev: '<<<< Previous',
    share: 'Share',
    notAvailable: 'Not Available',
    datanotFound: 'No Tickets Avaliable',
    PastEventNotAvailable:'You have no past events.',
    UpcommingEventNotAvailble:'You have no upcoming events at the moment.',
    disableAdmin:'Disabled By Admin'
  },
  // for update Profile Screen
  udpateProfile: {
    pageHeadding: 'Profile Setting',
    allowContact: 'Allow guest to contact you?',
    contactVia: 'Guest can contact you via:'
  },

  contactUs: {
    pageHeadding: 'Contact Us',
    selectIssue: 'Select Issue',
    message: 'Message',
    callUs: 'Or Call Us!',
    alertMsg: 'Thanks for contacting us!',
    note: 'Note : Please check your inbox for replies',
    callMsg: 'You can call us on',
    contactNumber: '+1 123 1234567',
    messagerequired: 'Message is required',
    issueIdRequired: 'Please select issue',
    messagePlaceholder: 'Write Here',
    customerSupport: 'Customer Support',
    customerSupportNumber: '1-866-881-LIVE (5483)',
    hostPromoter:'Event Promoters/Hosts',
    hostPromoterNumber:'1-800-365-3934',
    reachVia:'Or reach us via'



  },

  forgot: {
    forgotHead: 'Forgot Password',
    forgotDescription:
      'Don\'t worry we are here to help you please enter your registered email address to reset your password',
    labelemail: 'Email'
  },
  resetPassword: {
    resetPasswordHead: 'Reset Password',
    label: 'New Password',
    placholderNew: 'New Password',
    placholderConfirm: 'Confirm Password',
    resetConfirmationHead: 'Password Reset Successful',
  },
  headerSize: {
    large: 'large',
    medium: 'medium',
    small: 'small',
    betMedSmall: 'betMedSmall'
  },
  eventDetailPage: {
    havingTroubletext: 'Having trouble booking event?',
    contacthost: 'Please  Contact Host for Tickets & RSVP info',
    websiteUrlButton: 'Tickets & Seating'
  },

  // Payment methods
  paymentMethods: {
    pageHeadding: 'Payment Methods',
    addNewCard: 'Add new card',
    payNow: 'Pay Now',
    cardNumber: 'Card Number',
    placeHolder: 'Enter card number',
    expDate: 'Expiration date',
    cvv: 'CVV',
    billingAddress: 'Billing Address'
  },

  paymentTypes: {
    stripe: 'Stripe',
    paypal: 'Pay Pal',
    applePay: 'Apple Pay'
  },

  // create ticket
  createTicket: {
    ticketType: 'Ticket Type',
    ticketName: 'Ticket name',
    ticketQuantity: 'Total Tickets quantity',
    shortDescription: 'Enter short description',
    ticketDate: 'Ticket selling starts',
    anotherTicket: 'Add ticket',
    beforeCreateTicket: 'Ticket Should be added before continue',
    ticketNamePlaceholder: 'Enter Ticket name',
    ticketQuantityPlaceholder: 'Enter quantity',
    descriptionPlaceholder: 'Description',
    radioPaid: 'Paid',
    radioFree: 'Free',
    radioRSVP: 'RSVP',
    radioVIP: 'VIP',
    radioTables: 'Tables & Seatings',
    date: 'Date :',
    time: 'Time :',
    cancellation: 'Enter cancellation charges',
    mandatory: '( Minumum of 10% is mandatory)',
    number: 'Number of table',
    person: 'Person per table',
    priceTicket: 'Price per ticket',
    priceTable: 'Price per Table',
    priceTicketPlaceholder: 'Enter Price',
    categoryName: 'Category Name                                  Max-25 Words',
    tableName: 'Enter table name',
    publicEvent: 'Public Event',
    privateEvent: 'Private Event',
    frequency: 'Frequency',
    category: 'Category',
    tags: 'Tags',
    venueName: 'Venue Name',
    venueImage: 'Venue Image',
    description: 'Description',
    tickets: 'Tickets',
    AddDiscount:'Add Discount',
    DiscountPer:'Enter Discount % Per Ticket'
  },
  changepassword: {
    heading: 'Change Password',
    button: 'Change Password',
    labelold: 'Old Password',
    labelnew: 'New Password',
    labelconfir: 'Confirm Password'
  },
  RspvCheckbox: {
    selectAll: 'Select All',
    paid: 'Paid',
    free: 'Free',
    rspv: 'RSVP',
    vip: 'VIP',
    setting: 'Tables & Seatings',
    cancelled: 'Cancelled',
    searchLabel: 'Check-In with ticket number',
    CheckedIn: 'Checked-In-RSVPs',
    CheckedNotIn: 'Not Checked-In RSVPs',
    checkedHeader: 'Checked-in-RSVPs'
  },
  // Profile Setting
  ProfileLabel: {
    EditProfile: 'Edit Profile',
    ChangePassword: 'Change Password',
    EventReminder: 'Event Reminder',
    EventNotification: 'Event Notification',
    Notification: 'Notification',
    Share: 'Share',
    PrivacyPoilcy: 'Privacy',
    TermsUse: 'Terms of Use',
    faqs: 'FAQs',
  },
  //Manage user

  manageUser: {
    userListTitle: 'Manage Users',
    addNewUserTitle: 'Add New User',
    updateUserTitle: 'Update User',
    emptyUserList: 'This account does not have additional users at the moment',
    userType: 'User Type',
    fname: 'First Name',
    lname: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    password: 'Password',
    userFor: 'This Account Will be used to?',
    isMember: 'The default permission for the member is checked-in',
    save: 'Save',
    update: 'Update',
    userTypePholder: 'User Type',
    fnamePholder: 'Enter First Name',
    lnamePholder: 'Enter Last Name',
    emailPholder: 'Enter Email',
    phonePholder: 'Enter Pnone No.',
    passwordPholder: 'Enter Password',
    deleteUserAlertMsg: 'Are you sure you want to delete this User?',
    userType1: 'Host',
    userType2: 'Promoter',
    userType3: 'Member',
    role1: 'Create & List Events only',
    role2: 'Manage Users',
    role3: 'Both',
    //validation msg
    fnameValidate: 'Enter First Name',
    lnameValidate: 'Enter Last Name',
    validLetter: 'Enter only letters',
    emailValidate: 'Enter Email',
    emailValidatePattern: 'Enter valid Email',
    phoneValidate: 'Enter Phone No.',
    phoneValidatePattern: 'Enter number only',
    passwordValidate: 'Enter Password',



  },


  // create event
  SearchTicket: {
    searchLabel: ' Check-In with ticket number',
    ticketNumber: ' Enter the ticket number',
    searchTicket: ' Ticket No',
    TicketConfirmation: 'Ticket  check-In has been successfully.',
  },

  // create event
  createEvent: {
    EventType: 'Event Type',
    EventCategory: 'Event Category',
    SelectEventCategory: 'Select Event Category',
    SelectSubCategory: 'Select Sub Category',
    EventCreation: 'Event Creation',
    NameofEvent: 'Name of event',
    oftenEvent: 'How often is this event?',
    StartDate: 'Start Date',
    EndDate: 'End Date',
    StartTime: 'Start Time',
    EndTime: 'End Time',
    Selectvenue: 'Select a venue',
    galleryImages: 'Gallery Images',
    talentImages: 'Talent Images',
    sponserImages: 'Sponsor Images',
    venueImages: 'Venue Images',
    EventDetails: 'Event Details',
    AddonsInfo: 'Additional Information',
    PostEvent: 'Post Event',
    CreateTicket: 'Create Ticket/Seating',
    ImageUpload: '  ( First uploaded image will be set on the background of ticket and the event )',
    MaxWords: 'Max. 75 words',
    MaxMinWords: 'Min. 200 - Max. 2500 words',
    MinMaxWords: 'Max. 250 words',
    publicEvent: 'This is a Public Event',
    PrivateEvent: 'This is a Private  Event',
    OneTime: 'One Time',
    Daily: 'Daily',
    Weekly: 'Weekly',
    SelectedDays: 'Selected Days',
    NameofEventPlaceholder: 'Enter name of event',
    VenueNamePlaceholder: 'Select Venue Name',
    EventDetailsPlaceholder: 'Enter event details                                                        Min. 50 - Max. 4000 words',
    AddonsInfoPlaceholder: 'Enter add-on info',
    AddCustomeUUrl: 'Add Custome Url'
  },
  //editEvent
  editEvent: {
    updateEventAlertMsg: 'Are you sure you want to update this Event?',
    deleteEventAlertMsg: 'Are you sure you want to delete this Event?',
    deleteEventNote1: 'Note: By deleting this event, all purchased tickets for',
    deleteEventNote2: 'event will be auto-refunded',
  },

  subVenue: {
    twenty_minutes_alert: 'Your selected venue/sub-venue will be locked for 20 minutes. Please complete the event listing process to confirm this venue within that period of time.'
  },
  bookTicket: {
    noteLabel: 'Note : A 10% Non - Refundable deposit to book any table. The remaining balance will be collected at the door.',
    FreeTicket: 'Free Ticket',
    RegularTicket: 'Regular Ticket',
    VIPTicket: 'VIP Ticket',
    TableSeating: 'Tables & Seating',
    Basic: 'Basic',
    Premium: 'Premium',
    Description: 'This area is used to represent description of the basic free ticket',
    totaltickets: 'Select total tickets',
    YourTicket: 'Your Ticket',
    bookTicketSuccess: 'Thanks for booking the ticket!',
    emptyTicketCount: 'Please select ticket count'
  },
  searchVenue: {
    placholder: 'Enter a place  for Venue Search',
    distance: 'miles',
    miles: 'miles away',
    searchPlacholder: 'Search nearby venue',
    Subvenues: 'Sub-Venues'
  },
  rsvpInvite: {
    invitePageHeading: 'Send RSVP Invites',
    allContacts: 'All Contacts',
    pastAttendees: 'Past Attendees',
    search: 'Search by name',
    select: 'Select All',
    filter: 'filter',
    searchcountry: 'Search by Country',
  },
  viewEvent: {
    PageHeading: 'Events',
    Availability: 'Enter Availability',
    TotalRSVP: 'Total RSVP',
    CheckedRSVP: 'Checked-In RSVP',
    Totalpayment: 'Total payment',
    AllRSVP: 'View All RSVP',
    CheckedRSVPs: 'View Checked-In RSVP',
    AllPayment: 'View All Payment',
    RSVPInvites: 'Send RSVP Invites',
    EventDetail: 'Event Detail',
    EditEvent: 'Edit Event',
    EditTicket: 'Edit Ticket',
    RelatedEvent: 'Related Events'
  },
  groupTicket: {
    Pending: 'Pending',
    Accepted: 'Accepted',
    Tickets: 'Tickets',
    notification: 'Invitation is Accepted!',
    labelGroup: 'Purchased in a group',
    EventCode: 'Event Code',
    PendingRsvp:'',
    AcceptedRsvp:'You have no accepted RSVPS at the moment.',
    TicketsRsvp: 'You have no pending RSVPS at the moment.'
  },
  favorite: {
    favoritePageHeading: 'Favourite',
    past: 'Past',
    coming: 'Coming Soon',
    eventStart: 'Event Start',
    eventEnd: 'Event End'
  },
  bookedEvent: {
    bookedEventPageHeading: 'Booked Events',
    attended: 'Attended',
    coming: 'Coming Soon',
    eventStart: 'Event Start',
    eventEnd: 'Event End'
  },
  eventInfo: {
    eventInfoPageHeading: 'Events',
    past: 'Past Events',
    coming: 'Upcoming Events',
    search: 'Search Event'
  },
  createVenue: {
    VenueCreation: 'Create Venue',
    Availability: 'Make this venue available to other host?',
    Name: 'Name',
    address: 'Address',
    website: 'Website ( optional )',
    maxDec: 'Max. 2500 words',
    descriptionLabel: 'Description ( optional )',
    typeLabel: 'Type of Venue ( optional )',
    NamePlaceholder: 'Enter Venue Name',
    addressPlaceholder: 'Enter address of the venue',
    websitePlaceholder: 'eg: www.website.com',
    descriptionPlaceholder: 'Description',
    indoorRadioLabel: 'Indoor Venue',
    OutdoorRadioLabel: 'Outdoor Venue',
    capcityLabel: 'Venue Capacity ( optional )',
    capcityPlaceholder: 'eg: 100',
    checkBoxLabel: 'Add Sub - Venue ( optional )',
    subFormName: 'Sub - venue',
    subVenueNamePlaceholder: 'Enter name of sub - venue',
    subVenueCapcityPlaceholder: 'Enter capacity of sub - venue',
    operationLabel: 'Hours of Operation ( optional )',
    uploadPicture: 'Upload logo / Picture of the Venue ( optional )',
    optionalNote: 'If your primary venue has multiple sub-venue/ room / laws / halls / screens / etc use this option to create those and specify the sub - venue capacity.',
    editVenueHeading: 'Edit Venue'
  } ,
  venueLocation: {
    adminDisable: '"This venue is disable please contact administrator for support"'
  } ,
  editEventTicket: {
    editTicketPageHeading: 'Edit Tickets',
    note:
      'Note: Tickets can no longer be edited once a purchase is already made and all the tickets have to be returned before you can edit the tickets.',
    cancellation: 'Cancellation charge',
    ticketCost: '/ Ticket',
    ticketQuantity: 'Total Ticket',
    tableQuantity: 'No. of Tables',
  },
  customerReview: {
    reviewPageHeading: 'Customer Review',
    outOf: 'out of 5',
    ratingBase: 'Based on 200 rating',
    placeHolder: 'Type your review here',
    shareThoughts: 'Share your thoughts with others!',
  },
  chat: {
    chatPageHeading: 'Messages',
    conversation: 'conversation',
    search: 'search',
    noConversation: 'No conversations yet!',
    textAreaPlceholder: 'Type a message',
  },
  getpaid: {
    getpaidHeading: 'Get Paid',
    chooseAccountHeading: 'Choose account',
    confirmHeading: 'Confirm',
    WithdrawNow: 'Withdraw Now',
    confirmNote: 'Note: Transferred made before 8PM business days are processed the same day and usually completed within 2-3 days.',
    getPaidNote: 'Note: Your account has not been verified yet. Once verified, you will be able to withdraw funds 3 days after the event completion.'
  },
  notification: {
    Notification: 'Notifications',
    clearAll : 'CLEAR ALL',
    About: 'About',
    ago: 'ago',
    allNotification: 'See All Notifications',
    NotAvilable: 'Not Available'
  },
  addAccountPopup: {
    heading: 'Add New Account',
    subHeading: 'Please enter account details',
    routingNoLabel: 'Routing No.',
    bankNameLabel: 'Bank Name',
    accountNumberLabel: 'Account Number',
    subBtnText: 'Add Account'
  },
  paymentSubmitPopup: {
    description: 'Your request has been submitted and you will be notified once completed.',
    backhome: 'Back to home',
    transaction: 'Go to Transaction History',
    heading: 'Payment Request Submitted'
  },
  dataNotFound: {
    dataNfound : 'Data Not Available'
  },
  hostDetails: {
    enterContactDetails: 'Enter Contact Details',
    enterWebsiteDetails: 'Enter Website link',
    enterWebsiteToolTip: 'You can provide the event URL from different website. while ducking on Book Event this allows the user to redirect to different websites',
    unableToFetchDetails: 'Unable to get previous data',
    phoneNumber: 'Contact number is required',
    address: 'Address is required',
    webUrl : ' Website URL is required',
    textMessage: ' Choosing this option will not create any tickets to be purchased for your event. Please use the contact fields below to redirect users or connect users to your event for further information.s',
    autoFill:'Auto fill from previous data',
    atLeastOneCheck: 'Please select at least one check box'
  },
  recommondation: {
    pageHeadding : 'Recommendations'
  }
};
